command([[autocmd FileType defx lua setup_defx()]])

nmap('-', [[:Defx -split=vertical -winwidth=25 -direction=topleft -floating-preview `expand('%:p:h')` -search=`expand('%:p')`<CR>]])

function setup_defx()
  vim.wo.cursorline = true
  nnoremapBufferExpr('<CR>',    [[defx#do_action('multi', ['drop', 'quit'])]])
  nnoremapBufferExpr('c',       [[defx#do_action('copy')]])
  nnoremapBufferExpr('m',       [[defx#do_action('move')]])
  nnoremapBufferExpr('p',       [[defx#do_action('paste')]])
  nnoremapBufferExpr('l',       [[defx#do_action('open')]])
  nnoremapBufferExpr('E',       [[defx#do_action('multi', ['drop', 'quit'])]])
  nnoremapBufferExpr('P',       [[defx#do_action('preview')]])
  nnoremapBufferExpr('o',       [[defx#do_action('open_or_close_tree')]])
  nnoremapBufferExpr('K',       [[defx#do_action('new_directory')]])
  nnoremapBufferExpr('N',       [[defx#do_action('new_file')]])
  nnoremapBufferExpr('M',       [[defx#do_action('new_multiple_files')]])
  nnoremapBufferExpr('C',       [[defx#do_action('toggle_columns', 'mark:indent:icon:filename:type:size:time')]])
  nnoremapBufferExpr('S',       [[defx#do_action('toggle_sort', 'time')]])
  nnoremapBufferExpr('d',       [[defx#do_action('remove')]])
  nnoremapBufferExpr('r',       [[defx#do_action('rename')]])
  nnoremapBufferExpr('!',       [[defx#do_action('execute_command')]])
  nnoremapBufferExpr('x',       [[defx#do_action('execute_system')]])
  nnoremapBufferExpr('y',       [[defx#do_action('yank_path')]])
  nnoremapBufferExpr('.',       [[defx#do_action('toggle_ignored_files')]])
  nnoremapBufferExpr(';',       [[defx#do_action('repeat')]])
  nnoremapBufferExpr('h',       [[defx#do_action('cd', ['..'])]])
  nnoremapBufferExpr('~',       [[defx#do_action('cd')]])
  nnoremapBufferExpr('q',       [[defx#do_action('quit')]])
  nnoremapBufferExpr('c-Space>', [[defx#do_action('toggle_select') . 'j']])
  nnoremapBufferExpr('*',       [[defx#do_action('toggle_select_all')]])
  nnoremapBufferExpr('j',       [[line('.') == line('$') ? 'gg' : 'j']])
  nnoremapBufferExpr('k',       [[line('.') == 1 ? 'G' : 'k']])
  nnoremapBufferExpr('<C-l>',   [[defx#do_action('redraw')]])
  nnoremapBufferExpr('<C-g>',   [[defx#do_action('print')]])
  nnoremapBufferExpr('c',       [[defx#do_action('change_vim_cwd')]])
end
